name: atualiza-go
base: core22
version: '2.1'
summary: A modern graphical user interface for Linux system maintenance and updates.
description: |
  Atualiza GO is a graphical tool built with Wails to simplify Linux system updates. 
  It supports major distributions and handles system packages (APT, Pacman, DNF, Zypper, etc.), 
  as well as Flatpak and Snap ecosystems. It also includes a telemetry dashboard for RAM and Disk monitoring.

grade: stable
confinement: classic

icon: flatpak/io.github.erascardsilva.atualizago.png

apps:
  atualiza-go:
    command: bin/atualiza_go
    plugs:
      - network
      - network-bind
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - opengl
      - home

parts:
  frontend:
    plugin: npm
    source: frontend
    npm-node-version: 20.x
    npm-include-node: true
    build-packages:
      - nodejs
    override-build: |
      npm install
      npm run build
      cp -r dist $SNAPCRAFT_PART_INSTALL/dist

  atualiza-go:
    after: [frontend]
    plugin: go
    source: .
    build-snaps:
      - go/1.22/stable
    build-packages:
      - libwebkit2gtk-4.0-dev
      - libgtk-3-dev
      - pkg-config
    stage-packages:
      - libwebkit2gtk-4.0-37
      - libgtk-3-0
      - libglib2.0-0
    override-build: |
      mkdir -p frontend/dist
      cp -r $SNAPCRAFT_STAGE/dist/* frontend/dist/
      go build -o $SNAPCRAFT_PART_INSTALL/bin/atualiza_go .
