name: atualiza-go
base: core22
version: '2.1'
summary: A modern graphical user interface for Linux system maintenance and updates.
description: |
  Atualiza GO is a graphical tool built with Wails to simplify Linux system updates. 
  It supports major distributions and handles system packages (APT, Pacman, DNF, Zypper, etc.), 
  as well as Flatpak and Snap ecosystems. It also includes a telemetry dashboard for RAM and Disk monitoring.

grade: stable
confinement: classic

title: Atualiza GO
license: GPL-3.0
architectures:
  - amd64
icon: snap/gui/atualiza-go.png
apps:
  atualiza-go:
    command: bin/atualiza_go
    plugs:
      - network
      - network-bind
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - opengl
      - home

parts:
  atualiza-go:
    plugin: nil
    source: .
    build-snaps:
      - go/1.22/stable
      - node/20/stable
    build-environment:
      - GOTOOLCHAIN: local
    build-packages:
      - build-essential
      - libwebkit2gtk-4.0-dev
      - libgtk-3-dev
      - pkg-config
    stage-packages:
      - libwebkit2gtk-4.0-37
      - libgtk-3-0
      - libglib2.0-0
    override-build: |
      # Instala o Wails CLI
      go install github.com/wailsapp/wails/v2/cmd/wails@latest
      
      # Build do Frontend (NPM)
      npm install --prefix frontend
      
      # Build do Aplicativo com Wails (usando tags para webkit 4.0 do core22)
      ~/go/bin/wails build -m -tags webkit2_40 -nsis=false -upx=false -trimpath -o atualiza_go
      
      # Instalação no diretório do Snap
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp build/bin/atualiza_go $SNAPCRAFT_PART_INSTALL/bin/atualiza_go
