// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDistroInfo() {
  return window['go']['main']['App']['GetDistroInfo']();
}

export function GetSystemStats() {
  return window['go']['main']['App']['GetSystemStats']();
}

export function GetUpdateSteps() {
  return window['go']['main']['App']['GetUpdateSteps']();
}

export function RunSystemAction(arg1) {
  return window['go']['main']['App']['RunSystemAction'](arg1);
}

export function RunUpdate(arg1) {
  return window['go']['main']['App']['RunUpdate'](arg1);
}
