// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetDistroInfo():Promise<main.DistroInfo>;

export function GetSystemStats():Promise<main.SystemStats>;

export function GetUpdateSteps():Promise<Array<main.UpdateStep>>;

export function IsRestrictedSandbox():Promise<boolean>;

export function RunSystemAction(arg1:string):Promise<void>;

export function RunUpdate(arg1:Array<string>):Promise<void>;
